### PR TITLE
Update webkit.patch

### PR DESCRIPTION
**Pull request by turnerrocks1**

### CODE REVIEW

**Comment by turnerrocks1** [comment]
@saelo this needs your approval I think

**Comment by 0x41c** [comment]
You will need to click "CLA check for this pull request", then go to the section that says: "New Contributors". Agreeing to the CLA will approve the workflow allowing the pull request to get reviewed and possibly merged.

**Comment by turnerrocks1** [comment]
@0x41c "First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)[](https://github.com/apps/google-cla)
1 failing check
@google-cla"

**Comment by 0x41c** [comment]
Please click this link: https://github.com/googleprojectzero/fuzzilli/pull/336/checks?check_run_id=5763715531
Then go to the "New Contributors" section. That's where you'll be able to sign the CLA and have the workflow approved.

**Comment by turnerrocks1** [comment]
@0x41c thank you I appreciate you a lot I think it worked? This my first time every Doing a pull request and having to deal with this stuff

**Comment by saelo** [comment]
Can you please also update this file with the respective git revision: https://github.com/googleprojectzero/fuzzilli/blob/main/Targets/JavaScriptCore/REVISION thanks!

**Comment by turnerrocks1** [comment]
@saelo slight problem with that is I downloaded this on March 18th via webkit github "get code" - green button- no git clone or svn command method so I don't believe i can get the revision number ?

**Comment by turnerrocks1** [comment]
looking at the webkit commit hash this is what it is "4110e1b44a345737cdb807d36572c8714e90c5d0" so i put that in the revision file?

**Comment by saelo** [comment]
Looks good, thanks!

**Pull request merged**
