### PR TITLE
Update DuktapeBuilder/Dockerfile for latest duktape build system

### PR DESCRIPTION
**Pull request by lwizchz**
#193

### CODE REVIEW

**Comment by saelo** [comment]
Thanks for this @lwizchz! Can you also accept the CLA please? Then I can merge it :)

**Comment by lwizchz** [comment]
Yes, I'm working with my manager to figure out our process for signing CLAs. It's my first one so it may take some time, I'll understand if someone else comes up with an equivalent solution.

**Comment by saelo** [comment]
Ah sure, no worries! We can just keep this PR open, no rush :)

**Comment by lwizchz** [comment]
@googlebot I signed it!

**Comment by saelo** [comment]
Thanks!

**Pull request merged**
