### PR TITLE
Update JSC target revision to latest commit

### PR DESCRIPTION
**Pull request by drtychai**
For some odd reason the commit ref wasn't found in the latest clone (of `git://git.webkit.org/WebKit.git`)
```
git checkout ec7c3f75f3f3d7e5db6e92cf575563143c998a5f
fatal: reference is not a tree: ec7c3f75f3f3d7e5db6e92cf575563143c998a5f
```

Since the patch still applies cleanly, I just updated it to the [latest commit](https://bugs.webkit.org/attachment.cgi?id=415472&action=diff#a/Source/WebKit/ChangeLog_sec1) :)

### CODE REVIEW

**Comment by saelo** [comment]
Hmm odd, it seems there are two git mirrors for WebKit: https://git.webkit.org/ and somehow they have different commits:
https://git.webkit.org/?p=WebKit-https.git;a=commit;h=ec7c3f75f3f3d7e5db6e92cf575563143c998a5f exists, but
https://git.webkit.org/?p=WebKit.git;a=commit;h=ec7c3f75f3f3d7e5db6e92cf575563143c998a5f doesn't. I've used the WebKit-https one, mainly just because it's recommended here: https://webkit.org/getting-the-code/

**Comment by drtychai** [comment]
Huh, this is weird - I don't understand why that mirror exists.

Grepping through a fresh clone of both...
```sh
#!/bin/bash
WK_GIT_URI="git://git.webkit.org"
declare -a WK_REPOS=(
    "WebKit"
    "WebKit-https"
)

# (very) shallow clone
for WK_REPO in "${WK_REPOS[@]}"; do
  git clone -j`nproc` --depth 1 --single-branch --branch master ${WK_GIT_URI}/${WK_REPO}.git
done

# grep -iR  'webkit.org/webkit..' "${WK_REPOS[@]}"
rg -i 'webkit.org/webkit..' "${WK_REPOS[@]}"

read -r -p "[+] Delete repos? <y/N> " del
[[ "${del}" =~ "[yY][eE][sS]|[yY])" ]] && rm -rf "${WK_REPOS[@]}"
```

```sh
 ➜ ./hmm.sh
      [  ... ]
./WebKit/ReadMe.md
23:On Windows, follow the [instructions on our website](https://webkit.org/webkit-on-windows/).
30:git clone git://git.webkit.org/WebKit.git WebKit
141:For building WebKit on Windows, see the [wiki page](https://webkit.org/webkit-on-windows/).

./WebKit-https/ReadMe.md
23:On Windows, follow the [instructions on our website](https://webkit.org/webkit-on-windows/).
30:git clone git://git.webkit.org/WebKit.git WebKit
141:For building WebKit on Windows, see the [wiki page](https://webkit.org/webkit-on-windows/).

./WebKit/Tools/ChangeLog-2018-09-11
8702:        <https://webkit.org/webkit-on-windows/#installing-developer-tools>.

./WebKit/Tools/EWSTools/setup-commit-queue.sh
43:git clone git://git.webkit.org/WebKit.git WebKit

./WebKit/Tools/EWSTools/build-repo.sh
41:git clone git://git.webkit.org/WebKit.git webkit-$1

./WebKit-https/Tools/ChangeLog-2018-09-11
8702:        <https://webkit.org/webkit-on-windows/#installing-developer-tools>.

./WebKit-https/Tools/EWSTools/setup-commit-queue.sh
43:git clone git://git.webkit.org/WebKit.git WebKit

./WebKit-https/Tools/EWSTools/build-repo.sh
41:git clone git://git.webkit.org/WebKit.git webkit-$1
```

Every occurrence uses `git://git.webkit.org/WebKit.git` (even in the `WebKit-https` repo) 🤔 
- [README.md][wk]
- [WebKit on Windows][wk-win] 

[wk]: https://trac.webkit.org/browser/webkit/trunk/ReadMe.md#L25
[wk-win]: https://trac.webkit.org/browser/webkit/trunk/ReadMe.md#L25


Even better! If you search the domain ( `"webkit.org/webkit-https" site:webkit.org` )... only [6 results][gsearch], where 4 or 6 are related to the `WebKit-https` repo itself. The others are:
- [Getting the code][wk-get-code] (page you linked)
- [UsingGitWithWebKit][wk-using-git]

[gsearch]: https://www.google.com/search?q=%22webkit.org%2Fwebkit-https%22+site%3Awebkit.org
[wk-get-code]: https://webkit.org/getting-the-code/#getting-webkit
[wk-using-git]: https://trac.webkit.org/wiki/UsingGitWithWebKit#Checkout


FWIW I also noticed:
- [BuildingGtK][wk-gtk-get-src] contradicts [WebKitGTK/StartHacking][wk-gtk-hacking] in the GTK documentation, where the former links back to [Getting the code][wk-get-code]
- [JSCOnly][jsc] documents `WebKit.git`


[jsc]: https://trac.webkit.org/wiki/JSCOnly#Building
[wk-gtk-get-src]: https://trac.webkit.org/wiki/BuildingGtk#Gettingthesource
[wk-gtk-hacking]: https://trac.webkit.org/wiki/WebKitGTK/StartHacking#Gettingthesource

**Comment by saelo** [comment]
So I dug around a bit in the WebKit Slack, and it seems like the `-https` one is the recommended one (the difference is apparently that it uses svn over https in the background, while the other uses plaintext svn, and since the svn url is part of the commit message, the two have different git hashes...). The Github mirror is also set to use the `-https` one: ["mirrored from git://git.webkit.org/WebKit-https.git"](https://github.com/WebKit/webkit) (although the github mirror is currently broken). It also seems like they are planning to move to git completely in the near future. Anyway, for now I think we can stay on the `-https` clone but maybe note that explicitly in the README.md for the JavaScriptCore target. WDYT?

**Comment by drtychai** [comment]
I thought that might be the case, I just couldn't find it documented, oh well haha - yeah that SGTM 👍🏽

**Pull request closed without merging**
